// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","file":"@/pages/User/Login/index.tsx","parentId":"1","id":"2"},"3":{"path":"/welcome","name":"welcome","icon":"icon-zhuye1-copy","file":"@/pages/Welcome.tsx","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"list.activity-table-list","icon":"icon-icon_yingyongguanli","path":"/activity-list","file":"@/pages/ActivityTableList/index.tsx","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"list.apply-table-list","icon":"icon-shenhexiangmu","path":"/apply-list","file":"@/pages/ApplyTableList/index.tsx","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"user-management","icon":"icon-guanliyuan_jiaoseguanli","path":"/userManagement","file":"@/pages/UserManagement/index.tsx","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"personal-center","icon":"icon-wode-wode","path":"/uCenter","file":"@/pages/PersonalCenter/index.tsx","parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"*","layout":false,"file":"@/pages/404.tsx","id":"9"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","file":"@/.umi/plugin-layout/Layout.tsx","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi","file":"D:/Users/Desktop/myCode/bs_volunteerManagementSys/project_react/src/.umi/plugin-openapi/openapi.tsx"}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__ActivityTableList__index" */'@/pages/ActivityTableList/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__ApplyTableList__index" */'@/pages/ApplyTableList/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__UserManagement__index" */'@/pages/UserManagement/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__PersonalCenter__index" */'@/pages/PersonalCenter/index.tsx')),
'8': React.lazy(() => import( './EmptyRoute')),
'9': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'@/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'D:/Users/Desktop/myCode/bs_volunteerManagementSys/project_react/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
