# Generated by Django 2.2.6 on 2022-11-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='desc',
            field=models.CharField(max_length=255, verbose_name='活动描述'),
        ),
    ]
