// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import CrownOutlined from 'D:/Users/Desktop/myCode/bs_volunteerManagementSys/project_react/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'D:/Users/Desktop/myCode/bs_volunteerManagementSys/project_react/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { CrownOutlined, TableOutlined };
