// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/Users/Desktop/MyCode/volunteerManagementSys/project_react/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import HomeOutlined from 'D:/Users/Desktop/MyCode/volunteerManagementSys/project_react/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import CrownOutlined from 'D:/Users/Desktop/MyCode/volunteerManagementSys/project_react/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'D:/Users/Desktop/MyCode/volunteerManagementSys/project_react/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, HomeOutlined, CrownOutlined, TableOutlined };
