# Generated by Django 2.2.6 on 2022-11-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('desc', models.CharField(max_length=255, verbose_name='活动藐视')),
                ('publish_company_name', models.CharField(max_length=50, verbose_name='发布企业')),
                ('address', models.CharField(max_length=50, verbose_name='活动地点')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='开始日期')),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='开始时间')),
                ('demand', models.CharField(max_length=255, verbose_name='活动要求')),
                ('need_person_num', models.IntegerField(default=0, verbose_name='需要人数')),
                ('apple_person_num', models.IntegerField(default=0, verbose_name='已报名人数')),
                ('pass_person_num', models.IntegerField(default=0, verbose_name='已通过人数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '志愿者公益活动列表',
                'verbose_name_plural': '志愿者公益活动列表',
                'db_table': 'activity',
                'ordering': ['-create_time'],
            },
        ),
    ]
