# Generated by Django 2.2.6 on 2023-01-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20221107_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='apple_person_num',
            new_name='apply_person_num',
        ),
    ]
