# Generated by Django 2.2.6 on 2022-11-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20221108_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='tel',
            field=models.CharField(max_length=255, verbose_name='联系方式'),
        ),
    ]
