# Generated by Django 2.2.6 on 2022-11-08 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0002_auto_20221107_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('address', models.CharField(max_length=50, verbose_name='家庭住址')),
                ('tel', models.IntegerField(verbose_name='联系方式')),
                ('apply_status', models.IntegerField(choices=[(0, '待审核'), (1, '已审核'), (2, '未通过')], default=0, verbose_name='报名状态')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('belonging_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
            ],
            options={
                'verbose_name': '报名信息表',
                'verbose_name_plural': '报名信息表',
                'db_table': 'apply',
                'ordering': ['-apply_time'],
            },
        ),
    ]
