# Generated by Django 2.2.6 on 2022-11-08 03:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='联系方式'),
        ),
    ]
